server:
  port: 7020

spring:
  application:
    name: lzj-product-details
  profiles:
    active: mongodb, fastdfs, redis

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    service-url:
      defaultZone: http://192.168.10.102:8761/eureka/